schema_version: "1.0"

entry_point: app.py

runtime:
  type: python
  version: "3.10"

resources:
  sql_warehouse:
    warehouse_id: "e56d8ababeefe79f"  

command: ["streamlit", "run", "app.py"]

env:
  - name: "DATABRICKS_WAREHOUSE_ID"
    value: "e56d8ababeefe79f"

packages:
  - streamlit
  - pandas
  - numpy
  - plotly











